#!/usr/bin/env python3
"""
Detailed investigation of the split workout generation issue
"""

import requests
import json
from datetime import datetime

# Configuration
BACKEND_URL = "https://fstring-fix.preview.emergentagent.com/api"
TEST_USER_EMAIL = "testworkout@test.com"
TEST_USER_PASSWORD = "Test123!"

def investigate_split_generation():
    """Investigate the split generation issue in detail"""
    session = requests.Session()
    session.headers.update({'Content-Type': 'application/json'})
    
    # Login
    login_data = {"email": TEST_USER_EMAIL, "password": TEST_USER_PASSWORD}
    response = session.post(f"{BACKEND_URL}/auth/login", json=login_data)
    if response.status_code != 200:
        print("❌ Login failed")
        return
    
    print("✅ Login successful")
    
    # Generate the same workout as in the test
    payload = {
        "objective": "hipertrofia",
        "level": "intermediario",
        "generation_mode": "tipo_treino",
        "split_type": "ABC",
        "split_config": [
            {"label": "A", "name": "Peito e Tríceps", "muscle_groups": ["peito", "triceps"]},
            {"label": "B", "name": "Costas e Bíceps", "muscle_groups": ["costas", "biceps"]},
            {"label": "C", "name": "Pernas e Abdômen", "muscle_groups": ["pernas", "abdomen", "gluteos"]}
        ],
        "training_days_per_week": 7,
        "cycle_weeks": 4,
        "include_cardio": True,
        "cardio_type": "corrida",
        "duration": "ciclo"
    }
    
    print("🚀 Generating workout plan...")
    response = session.post(f"{BACKEND_URL}/workout-plans/generate", json=payload, timeout=120)
    
    if response.status_code != 200:
        print(f"❌ Generation failed: {response.status_code} - {response.text}")
        return
    
    data = response.json()
    plan = data.get("plan", {})
    days = plan.get("days", [])
    
    print(f"\n📊 DETAILED ANALYSIS:")
    print(f"Total days: {len(days)}")
    print(f"Expected days: 28 (7 days × 4 weeks)")
    
    # Analyze each day
    days_with_exercises = 0
    days_without_exercises = 0
    split_distribution = {}
    
    for i, day in enumerate(days):
        exercises = day.get("exercises", [])
        week = day.get("week", "?")
        split_label = day.get("split_label", "?")
        day_name = day.get("day_name", "?")
        
        if exercises:
            days_with_exercises += 1
        else:
            days_without_exercises += 1
            print(f"❌ Day {i+1} ({day_name}) has NO exercises - Week {week}, Split {split_label}")
        
        # Count split distribution
        if split_label not in split_distribution:
            split_distribution[split_label] = 0
        split_distribution[split_label] += 1
    
    print(f"\n📈 SUMMARY:")
    print(f"Days with exercises: {days_with_exercises}")
    print(f"Days without exercises: {days_without_exercises}")
    print(f"Split distribution: {split_distribution}")
    
    # Show first few days for pattern analysis
    print(f"\n🔍 FIRST 10 DAYS PATTERN:")
    for i in range(min(10, len(days))):
        day = days[i]
        exercises = day.get("exercises", [])
        week = day.get("week", "?")
        split_label = day.get("split_label", "?")
        day_name = day.get("day_name", "?")
        print(f"Day {i+1}: {day_name} | Week {week} | Split {split_label} | {len(exercises)} exercises")
    
    # Check if cardio split was generated
    splits = plan.get("splits", [])  # This would be from the AI response
    print(f"\n🏃 CARDIO ANALYSIS:")
    print(f"Number of splits generated by AI: {len(splits) if splits else 'N/A'}")
    
    if splits:
        for split in splits:
            label = split.get("split_label", "?")
            name = split.get("split_name", "?")
            exercises = split.get("exercises", [])
            print(f"Split {label}: {name} ({len(exercises)} exercises)")

if __name__ == "__main__":
    investigate_split_generation()